config/routes.rb
Questify::Application.routes.draw do
  resources :questions do 
    member do
     post 'answer', to: 'questions#answer'
    end
  end

  resources :teachers

  resources :users

  root to: 'questions#index'

  

end

app/models/question.rb
class Question < ActiveRecord::Base
belongs_to :user
belongs_to :teacher

validates_presence_of :user_id

  def self.latest
    Question.order(:updated_at).last
  end

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  
  has_many :questions

  validates :name, uniqueness: true, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions


  validates :name, uniqueness: true, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    #@questions = Question.includes(:user).all
    @questions = Question.where(status: false)
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.includes(:user, :teacher).find(params[:id])

  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @users = User.all
    @teachers = Teacher.all
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render action: 'show', status: :created, location: @question }
      else
        format.html { render action: 'new' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def answer
    @question = Question.includes(:user, :teacher).find(params[:id])
    if @question.status
      @question.status = false
    else
      @question.status = true
    end
    @question.save
    redirect_to questions_path
  end


  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:topic, :question, :status, :user_id, :teacher_id)
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render action: 'show', status: :created, location: @teacher }
      else
        format.html { render action: 'new' }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :photo_url)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :photo_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hacker Q</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script type="text/javascript" src="http://twitter.github.com/bootstrap/assets/js/bootstrap-dropdown.js"></script>

</head>
<body>
  <META HTTP-EQUIV="refresh" CONTENT="100">


<div class="container-fluid">	
<div class="header">
<%= link_to image_tag("hackerQ.png"), questions_path %>
</div>



<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <ul class="nav">
      <li class="active"><%= link_to 'Home', questions_path %></li>
      <li><%= link_to 'New Question', new_question_path %></li>
      
      
      
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Users
          <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Users', users_path %></li>
          <li><%= link_to 'Add User', new_user_path %></li>
        </ul>
      </li>
      
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Teachers
          <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Teachers', teachers_path %></li>
          <li><%= link_to 'Add Teacher', new_teacher_path %></li>
        </ul>
      </li>


    </ul>
  </div>
</div>

<br>
<br>


<%= yield %>
</div>
</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question, html: { class: "form-horizontal" }) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <div><%= f.label :topic %></div>
    <div><%= f.text_field :topic %></div>
  </div>
  <div>
    <div><%= f.label :question %></div>
    <div><%= f.text_area :question %></div>
  </div>
  <div>
    <div><%= f.label :user %></div>
    <div><%= collection_select(:question, :user_id, User.all, :id, :name, {:prompt=>true}) %></div>
  </div>
  <div>
    <div><%= f.label :teacher %></div>
    <div><%= collection_select(:question, :teacher_id, Teacher.all, :id, :name, {:prompt=>true}) %></div>
  </div>
<br>

<%= f.label :status %>

<%= f.submit :class=>"btn btn-success"%>
 
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>
<br>
<br>

<%= link_to 'Show', @question, :class=> "btn" %> 
<%= link_to 'Back', questions_path, :class=> "btn" %>

app/views/questions/index.html.erb
<h1>Today's Questions</h1>



<br>
<table class="table table-hover">
  <% @questions.each do |question| %>


    
    <% tag :tr,  id: dom_id(question) %>
    <tr id="<%= dom_id(question) %>">
      <td>
        <h4>Question #<%= question.id %></h4>
        <%= image_tag(question.user.photo_url, class: 'img-circle') %><br> 
       <h4><%= question.user.name %></h4>
      </td>
      <td class="span10">
        <div class="well">
          <h3><%= question.topic %></h3>
          <%= question.question %>
        </div> 
        <p>Created: <%= time_ago_in_words(question.created_at) %></p>
      </td>
      <td>
        <h4><%= question.teacher.name %></h4>
        <%= image_tag(question.teacher.photo_url, class: 'img-circle') %><br> 
        
      </td>
      <td>
        <%= button_to 'Answered', answer_question_path(question), :class=>"question-state-button" %><br>
        <%= link_to 'Edit', edit_question_path(question), :class=>"btn btn-primary" %><br>
        <%= link_to 'Delete', question, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger" %>
     </td>
   </tr>
 
    
<% end %>
</table> 

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>
<br>
<br>

<%= link_to 'Back', questions_path, :class=> "btn" %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Topic:</strong>
  <%= @question.topic %>
</p>

<p>
  <strong>Question:</strong>
  <%= @question.question %>
</p>

<p>
  <strong>Status:</strong>
  <%= @question.status %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

app/views/teachers/_form.html.erb
<%= form_for(@teacher, html: { class: "form-horizontal" }) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label :photo_url %>
    <%= f.text_field :photo_url %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit :class=>"btn btn-success"%>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<h1>HackerYou Teachers</h1>

    <% @teachers.each do |teacher| %>
      <div class="thumbnail span2">
        
            <%= image_tag(teacher.photo_url, class: 'img-rounded') %>
            <center><h5><%= teacher.name %></h5></center>
            <center>
            <%= link_to 'Edit', edit_teacher_path(teacher), :class=>"btn btn-primary" %>
            <%= link_to 'Delete', teacher, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger"  %>
            </center>
      </div>
    <% end %>

app/views/teachers/new.html.erb
<h1>New teacher</h1>

<%= render 'form' %>



<%= link_to 'Back', teachers_path, :class=> "btn"  %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @teacher.name %>
</p>

<p>
  <strong>Photo url:</strong>
  <%= @teacher.photo_url %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>

app/views/users/_form.html.erb
<%= form_for(@user, html: { class: "form-horizontal" }) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label :photo_url %>
    <%= f.text_field :photo_url %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit :class=>"btn btn-success"%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>HackerYou Students</h1>

    <% @users.each do |user| %>
      <div class="thumbnail span2">
        
            <%= image_tag(user.photo_url, class: 'img-rounded') %>
            <center><h5><%= user.name %></h5></center>
            <center>
            <%= link_to 'Edit', edit_user_path(user), :class=>"btn btn-primary" %>
            <%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger"  %>
            <center>
      </div>
    <% end %>


<br>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path, :class=> "btn" %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Photo url:</strong>
  <%= @user.photo_url %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>